language: c++
compiler:
  - clang
  - gcc

os: linux
dist: xenial

before_install:
  - sudo apt-get update
  - sudo apt-get upgrade -y
  # Python builds are not working on Travis so skip them
  #  - sudo apt-get install -y python3-all python3-all-dev libpython3-all-dev python3-setuptools
  #  - sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 1
  #  - sudo update-alternatives --set python /usr/bin/python3
  - mkdir ./cmake_build
  - cd ./cmake_build
  - cmake -DCMAKE_BUILD_TYPE=DEBUG -DLIBMINISYNCPP_BUILD_TESTS=TRUE -DLIBMINISYNCPP_BUILD_DEMO=TRUE ..

script:
  - cmake --build . --target all -- -j 4

# testing
after_success:
  - ./tests/minisyncpp
