language: c++
compiler:
  - clang
  - gcc

os: linux
dist: xenial

before_install:
  - mkdir ./cmake_build
  - cd ./cmake_build
  - >-
  cmake
  -DCMAKE_BUILD_TYPE=DEBUG
  -DLIBMINISYNCPP_BUILD_TESTS=TRUE
  -DLIBMINISYNCPP_BUILD_DEMO=TRUE
  -DLIBMINISYNCPP_WITH_PYTHON=TRUE ..

script:
  - cmake --build . --target all -- -j 4

# testing
after_success:
  - ./tests/minisyncpp
