language: c++
compiler:
  - clang
  - gcc

os: linux
dist: xenial

before_install:
  - mkdir ./cmake_build
  - cd ./cmake_build
  - cmake -DCMAKE_BUILD_TYPE:STRING=DEBUG ..

script:
  - cmake --build . --target all -- -j 4

# testing
after_success:
  - ./tests/minisyncpp --success
